# Library Initialization

In [153]:
import pandas as pd

# Dataset Exploration

In [154]:
data = pd.read_csv("data/alien_visitors.csv")
data.head(5)

   Visitor_ID  Name   Planet    Age Favorite_Food
0         101  Zorx     Mars  120.0         Pizza
1         102  Niko     mars   95.0        Burger
2         103  Luna  Jupiter    NaN         Sushi
3         104  Xeno   SATURN  150.0           NaN
4         105  Nova   saturn    NaN         Tacos

In [155]:
data.tail(5)

    Visitor_ID     Name    Planet    Age Favorite_Food
26         126    Flare    saturn    NaN         Pizza
27         127    Comet   JUPITER  111.0        Burger
28         128   Galaxy   NEPTUNE  136.0         Sushi
29         129  Phoenix      mars    NaN         Tacos
30         130   Nebula    SATURN  147.0           NaN

In [156]:
data.shape

(31, 5)

In [157]:
data.columns

Index(['Visitor_ID', 'Name', 'Planet', 'Age', 'Favorite_Food'], dtype='str')

In [158]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Visitor_ID     31 non-null     int64
 1   Name           31 non-null     str
 2   Planet         31 non-null     str
 3   Age            21 non-null     float64
 4   Favorite_Food  26 non-null     str
dtypes: float64(1), int64(1), str(3)
memory usage: 1.3 KB

In [159]:
data.describe()

       Visitor_ID         Age
count   31.000000   21.000000
mean   115.096774  126.285714
std      8.941867   15.254976
min    101.000000   95.000000
25%    107.500000  115.000000
50%    115.000000  128.000000
75%    122.500000  138.000000
max    130.000000  150.000000

Data contains 5 coloumns, 3 str, 1 float, int, there are missing values

# Missing Values Investigation

In [160]:
null = data.isnull().sum()
null

Visitor_ID        0
Name              0
Planet            0
Age              10
Favorite_Food     5
dtype: int64

In [161]:
null / len(data) * 100

Visitor_ID        0.000000
Name              0.000000
Planet            0.000000
Age              32.258065
Favorite_Food    16.129032
dtype: float64

The column "Age" has the heighst number of missing values

# Duplicate Records Detection

In [162]:
data_cleaned = data

In [163]:
data_cleaned.duplicated().sum()

np.int64(1)

In [164]:
data_cleaned = data_cleaned.drop_duplicates()
data_cleaned.duplicated().sum()

np.int64(0)

We notice that sum of dublicated records becames 0

# Planet Names Standardization

In [165]:
column = data_cleaned["Planet"]
column

0         Mars
1         mars
2      Jupiter
3       SATURN
4       saturn
5         Mars
6      JUPITER
7      Neptune
8      neptune
9         MARS
10      Saturn
11     Jupiter
12        mars
13     NEPTUNE
14     Jupiter
15      saturn
17        Mars
18     Neptune
19        MARS
20     JUPITER
21        mars
22      SATURN
23     jupiter
24     Neptune
25        MARS
26      saturn
27     JUPITER
28     NEPTUNE
29        mars
30      SATURN
Name: Planet, dtype: str

In [166]:
data_cleaned["Planet"] = column.str.strip().str.lower()
data_cleaned["Planet"]

0        mars
1        mars
2     jupiter
3      saturn
4      saturn
5        mars
6     jupiter
7     neptune
8     neptune
9        mars
10     saturn
11    jupiter
12       mars
13    neptune
14    jupiter
15     saturn
17       mars
18    neptune
19       mars
20    jupiter
21       mars
22     saturn
23    jupiter
24    neptune
25       mars
26     saturn
27    jupiter
28    neptune
29       mars
30     saturn
Name: Planet, dtype: str

Here the text standardization was important because there was a messy data (different format)

# Missing Values Handling

In [167]:
age = data_cleaned["Age"]
food = data_cleaned["Favorite_Food"]
mean = age.mean()
mode = food.mode()[0]
print(f"mean age: {mean}, median age: {age.median()}")
print(f"most frequent food value: {mode}")

mean age: 126.28571428571429, median age: 128.0
most frequent food value: Pizza

In [168]:
data_cleaned["Age"] = age.fillna(mean)
data_cleaned["Favorite_Food"] = food.fillna("Unknown")
data_cleaned.isnull().sum()

Visitor_ID       0
Name             0
Planet           0
Age              0
Favorite_Food    0
dtype: int64

# Planet Distribution Analysis

In [169]:
data_cleaned["Planet"].value_counts()

Planet
mars       10
jupiter     7
saturn      7
neptune     6
Name: count, dtype: int64

Mars has the highest number of visitors

# Food Preference Analysis

In [170]:
data_cleaned["Favorite_Food"].value_counts()

Favorite_Food
Pizza      7
Burger     6
Unknown    5
Tacos      5
Sushi      4
Noodles    3
Name: count, dtype: int64

The most popular food among visitors is "Pizza"

# Age Group Creation

In [171]:
data_cleaned["Age_Group"] = pd.cut(data_cleaned["Age"], bins = 3, labels = ["Young", "Adult", "Senior"])
data_cleaned["Age_Group"].value_counts()

Age_Group
Adult     16
Senior     9
Young      5
Name: count, dtype: int64

# Insight Generation

In [176]:
print(f"""
average visitor age: {mean}
most common planet: {data_cleaned["Planet"].mode()[0]}
most popular food: {mode}
most frequent age group: {data_cleaned["Age_Group"].mode()[0]}
""")

average visitor age: 126.28571428571429
most common planet: mars
most popular food: Pizza
most frequent age group: Adult

At the end, we notice that data preperation improved the dataset and made it more accurate and not messy, and these cleaning steps were important before analysis because they prevent the inaccurate analysis

In [179]:
data_cleaned.to_csv("data/alien_visitors_cleaned.csv", index = False)