In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv("data\store_inventory.csv")
df.head(3)

   Order_ID   Product     Category   Price  Quantity      Date
0       101    Laptop  Electronics  1200.0       1.0  1/1/2024
1       102     Mouse  Electronics    25.0       2.0  1/2/2024
2       103  Keyboard  Electronics    50.0       1.0  1/2/2024

In [6]:
df.tail(4)

   Order_ID     Product     Category  Price  Quantity      Date
3       104  Desk Chair    Furniture  150.0       3.0  1/3/2024
4       105     Monitor  Electronics  300.0       NaN  1/4/2024
5       106        Lamp    Furniture   40.0       2.0  1/5/2024
6       107  Headphones  Electronics    NaN       1.0  1/6/2024

In [7]:
df.sample(3)

   Order_ID     Product     Category   Price  Quantity      Date
0       101      Laptop  Electronics  1200.0       1.0  1/1/2024
3       104  Desk Chair    Furniture   150.0       3.0  1/3/2024
6       107  Headphones  Electronics     NaN       1.0  1/6/2024

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  7 non-null      int64
 1   Product   7 non-null      str
 2   Category  7 non-null      str
 3   Price     6 non-null      float64
 4   Quantity  6 non-null      float64
 5   Date      7 non-null      str
dtypes: float64(2), int64(1), str(3)
memory usage: 468.0 bytes

In [13]:
df.describe()

         Order_ID        Price  Quantity
count    7.000000     6.000000  6.000000
mean   104.000000   294.166667  1.666667
std      2.160247   455.636002  0.816497
min    101.000000    25.000000  1.000000
25%    102.500000    42.500000  1.000000
50%    104.000000   100.000000  1.500000
75%    105.500000   262.500000  2.000000
max    107.000000  1200.000000  3.000000

In [14]:
df.isnull().sum()

Order_ID    0
Product     0
Category    0
Price       1
Quantity    1
Date        0
dtype: int64

In [15]:
df["Price"] = df["Price"].fillna(df["Price"].mean())
df["Quantity"] = df["Quantity"].fillna(0)

In [16]:
df.isnull().sum()

Order_ID    0
Product     0
Category    0
Price       0
Quantity    0
Date        0
dtype: int64

In [18]:
df["Revenue"] = df["Price"] * df["Quantity"]

In [19]:
df.head()

   Order_ID     Product     Category   Price  Quantity      Date  Revenue
0       101      Laptop  Electronics  1200.0       1.0  1/1/2024   1200.0
1       102       Mouse  Electronics    25.0       2.0  1/2/2024     50.0
2       103    Keyboard  Electronics    50.0       1.0  1/2/2024     50.0
3       104  Desk Chair    Furniture   150.0       3.0  1/3/2024    450.0
4       105     Monitor  Electronics   300.0       0.0  1/4/2024      0.0

In [21]:
df[df["Price"] > 100]

,Order_ID,Product,Category,Price,Quantity,Date,Revenue
0,101,Laptop,Electronics,1200.000000,1.0,1/1/2024,1200.000000
3,104,Desk Chair,Furniture,150.000000,3.0,1/3/2024,450.000000
4,105,Monitor,Electronics,300.000000,0.0,1/4/2024,0.000000
6,107,Headphones,Electronics,294.166667,1.0,1/6/2024,294.166667

In [ ]:
df.to_csv("data/cleaned_data.csv", index = False)