# Library Initialization

In [2]:
import pandas as pd

# Dataset Exploration

In [3]:
df = pd.read_csv("data/space_delivery_employees.csv")
df.head(5)

   Employee_ID   Planet  Department Performance_Level  Monthly_Deliveries
0         1001     Mars   Logistics              High                 520
1         1002  Jupiter  Operations            Medium                 430
2         1003   Saturn   Logistics               Low                 280
3         1004  Neptune     Support              High                 610
4         1005     Mars  Operations            Medium                 450

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         20 non-null     int64
 1   Planet              20 non-null     str
 2   Department          20 non-null     str
 3   Performance_Level   20 non-null     str
 4   Monthly_Deliveries  20 non-null     int64
dtypes: int64(2), str(3)
memory usage: 932.0 bytes

In [5]:
df.columns

Index(['Employee_ID', 'Planet', 'Department', 'Performance_Level',
       'Monthly_Deliveries'],
      dtype='str')

In [6]:
df.shape

(20, 5)

The columns "Employee_ID" and "Monthly_Deliveries" are numerical, and the columns "Planet", "Department" and "Performance_Level" are categorical

# Data Type Investigation:

In [7]:
df.dtypes

Employee_ID           int64
Planet                  str
Department              str
Performance_Level       str
Monthly_Deliveries    int64
dtype: object

performance level may need to be converted to numerical column

# Department Frequency Analysis

In [8]:
df.drop_duplicates()
df["Department"].value_counts()

Department
Logistics     7
Operations    7
Support       6
Name: count, dtype: int64

Logistics and operations are the most common department

# Label Encoding – Performance Level

In [9]:
df["Performance_Encoded"] = df["Performance_Level"].map({"Low": 0, "Medium": 1, "High": 2})
df["Performance_Encoded"]

0     2
1     1
2     0
3     2
4     1
5     2
6     0
7     1
8     2
9     1
10    0
11    2
12    1
13    2
14    1
15    0
16    2
17    1
18    0
19    2
Name: Performance_Encoded, dtype: int64

# One-Hot Encoding

In [10]:
df = pd.get_dummies(df, columns = ["Planet", "Department"])
df

,Employee_ID,Performance_Level,Monthly_Deliveries,Performance_Encoded,Planet_Jupiter,Planet_Mars,Planet_Neptune,Planet_Saturn,Department_Logistics,Department_Operations,Department_Support
0,1001,High,520,2,False,True,False,False,True,False,False
1,1002,Medium,430,1,True,False,False,False,False,True,False
2,1003,Low,280,0,False,False,False,True,True,False,False
3,1004,High,610,2,False,False,True,False,False,False,True
4,1005,Medium,450,1,False,True,False,False,False,True,False
5,1006,High,560,2,True,False,False,False,True,False,False
6,1007,Low,260,0,False,False,False,True,False,False,True
7,1008,Medium,410,1,False,False,True,False,False,True,False
8,1009,High,590,2,False,True,False,False,True,False,False
9,1010,Medium,390,1,True,False,False,False,False,False,True
10,1011,Low,300,0,False,False,False,True,False,True,False
11,1012,High,620,2,False,False,True,False,True,False,False
12,1013,Medium,370,1,False,True,False,False,False,False,True
13,1014,High,540,2,True,False,False,False,False,True,False
14,1015,Medium,460,1,False,False,False,True,True,False,False
15,1016,Low,250,0,False,False,True,False,False,False,True
16,1017,High,570,2,False,True,False,False,False,True,False
17,1018,Medium,440,1,True,False,False,False,True,False,False
18,1019,Low,290,0,False,False,False,True,False,False,True
19,1020,High,600,2,False,False,True,False,False,True,False

# Normalization – Monthly Deliveries:

In [12]:
column = df["Monthly_Deliveries"]
df["Deliveries_Normalized"] = (column - column.min()) / (column.max() - column.min())
print(df["Deliveries_Normalized"].min(), df["Deliveries_Normalized"].max())

0.0 1.0

# Standardization – Monthly Deliveries

In [13]:
column = df["Monthly_Deliveries"]
df["Deliveries_Standardized"] = (column - column.mean()) / column.std()
print(df["Deliveries_Standardized"].mean(), df["Deliveries_Standardized"].std())

-1.1102230246251566e-17 1.0

# Comparison Analysis

In [21]:
df[["Monthly_Deliveries", "Deliveries_Normalized", "Deliveries_Standardized"]]

    Monthly_Deliveries  Deliveries_Normalized  Deliveries_Standardized
0                  520               0.729730                 0.579773
1                  430               0.486486                -0.135016
2                  280               0.081081                -1.326329
3                  610               0.972973                 1.294561
4                  450               0.540541                 0.023826
5                  560               0.837838                 0.897456
6                  260               0.027027                -1.485171
7                  410               0.432432                -0.293857
8                  590               0.918919                 1.135719
9                  390               0.378378                -0.452699
10                 300               0.135135                -1.167487
11                 620               1.000000                 1.373982
12                 370               0.324324                -0.611541
13                 540               0.783784                 0.738615
14                 460               0.567568                 0.103247
15                 250               0.000000                -1.564592
16                 570               0.864865                 0.976877
17                 440               0.513514                -0.055595
18                 290               0.108108                -1.246908
19                 600               0.945946                 1.215140

In [18]:
df[["Monthly_Deliveries", "Deliveries_Standardized"]].agg(["mean", "std"])

      Monthly_Deliveries  Deliveries_Standardized
mean          447.000000            -1.110223e-17
std           125.911414             1.000000e+00

In [20]:
columns = df[["Monthly_Deliveries", "Deliveries_Normalized"]]
print(columns.max(), columns.min())

Monthly_Deliveries       620.0
Deliveries_Normalized      1.0
dtype: float64 Monthly_Deliveries       250.0
Deliveries_Normalized      0.0
dtype: float64

# Final Dataset Review

In [22]:
df

,Employee_ID,Performance_Level,Monthly_Deliveries,Performance_Encoded,Planet_Jupiter,Planet_Mars,Planet_Neptune,Planet_Saturn,Department_Logistics,Department_Operations,Department_Support,Deliveries_Normalized,Deliveries_Standardized
0,1001,High,520,2,False,True,False,False,True,False,False,0.729730,0.579773
1,1002,Medium,430,1,True,False,False,False,False,True,False,0.486486,-0.135016
2,1003,Low,280,0,False,False,False,True,True,False,False,0.081081,-1.326329
3,1004,High,610,2,False,False,True,False,False,False,True,0.972973,1.294561
4,1005,Medium,450,1,False,True,False,False,False,True,False,0.540541,0.023826
5,1006,High,560,2,True,False,False,False,True,False,False,0.837838,0.897456
6,1007,Low,260,0,False,False,False,True,False,False,True,0.027027,-1.485171
7,1008,Medium,410,1,False,False,True,False,False,True,False,0.432432,-0.293857
8,1009,High,590,2,False,True,False,False,True,False,False,0.918919,1.135719
9,1010,Medium,390,1,True,False,False,False,False,False,True,0.378378,-0.452699
10,1011,Low,300,0,False,False,False,True,False,True,False,0.135135,-1.167487
11,1012,High,620,2,False,False,True,False,True,False,False,1.000000,1.373982
12,1013,Medium,370,1,False,True,False,False,False,False,True,0.324324,-0.611541
13,1014,High,540,2,True,False,False,False,False,True,False,0.783784,0.738615
14,1015,Medium,460,1,False,False,False,True,True,False,False,0.567568,0.103247
15,1016,Low,250,0,False,False,True,False,False,False,True,0.000000,-1.564592
16,1017,High,570,2,False,True,False,False,False,True,False,0.864865,0.976877
17,1018,Medium,440,1,True,False,False,False,True,False,False,0.513514,-0.055595
18,1019,Low,290,0,False,False,False,True,False,False,True,0.108108,-1.246908
19,1020,High,600,2,False,False,True,False,False,True,False,0.945946,1.215140

The newly created columns: Performance_Encoded, Planet_Jupiter, Planet_Mars, Planet_Neptune, Planet_Saturn, Department_Logistics, Department_Operations, Department_Support, Deliveries_Normalized, and Deliveries_Standardized

# Insight Generation

In [31]:
df[["Department_Logistics", "Department_Operations", "Department_Support"]].sum()

Department_Logistics     7
Department_Operations    7
Department_Support       6
dtype: int64

The "Logistics" and "Operations" departments have the heighest number of employees

In [32]:
df[["Planet_Jupiter", "Planet_Mars", "Planet_Neptune", "Planet_Saturn"]].sum()

Planet_Jupiter    5
Planet_Mars       5
Planet_Neptune    5
Planet_Saturn     5
dtype: int64

All planets has the same number of employees

- Label Encoding: Converts categories into numeric values. Best for ordinal data.

- One-Hot Encoding: Converts each category into a separate binary column. Best for nominal data where no order exists.

- Normalization: Scales values into a fixed range (usually 0–1). Useful for machine learning.

- Standardization: it makes mean = 0 and standard deviation = 1. Useful for machine learning.

In [33]:
df.to_csv("data/space_delivery_employees_prepared.csv", index = False)